apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    run: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mysql
  template:
    metadata:
      labels:
        run: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_USER
          value: ubuntu
        - name: MYSQL_PASSWORD
          value: "1234"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    run: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flask
  template:
    metadata:
      labels:
        run: flask
    spec:
      containers:
      - name: flask
        image: hongkunyoo/flask
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: ubuntu
        - name: MYSQL_PASSWORD
          value: "1234"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: conf
        - mountPath: /usr/share/nginx/html
          name: conf
      volumes:
      - name: conf
        hostPath:
          path: /home/ubuntu/do-it-more