apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: flask
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: flask
  name: flask
spec:
  containers:
  - image: hongkunyoo/flask
    name: flask
    env:
    - name: MYSQL_HOST
      value: "mysql"
    - name: MYSQL_USER
      value: ubuntu
    - name: MYSQL_PASSWORD
      value: "1234"